"""
Convert paper/submit_ready.md (and review_manuscript.md for the long form) into
the LaTeX fragments used by paper/Formatting_Instructions_For_NeurIPS_2026/main_short.tex
(and main.tex). Idempotent — safe to re-run any time the markdown changes.

Outputs (short / submission form):
  _abstract_short.tex   — abstract body (no \begin{abstract} wrapper; main_short.tex wraps it)
  body_main_short.tex   — sections 1..9 of the main paper
  refs_short.tex        — references section
  body_appendix.tex     — appendices A..F + Z (extended discussion)

The pre-existing tex files were generated by an earlier pandoc run that
treated some unicode whitespace as U+00A0, producing tildes between every
word. The current markdown source has 0 nbsp, so a clean pandoc run on the
current source produces clean LaTeX.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUBMIT_MD = ROOT / "submit_ready.md"
REVIEW_MD = ROOT / "review_manuscript.md"
LATEX_DIR = ROOT / "Formatting_Instructions_For_NeurIPS_2026"


def split_md(md: str) -> dict[str, str]:
    """Split submit_ready.md into (yaml, body sections by H1)."""
    yaml_match = re.match(r"^---\n(.*?)\n---\n", md, re.DOTALL)
    yaml = yaml_match.group(1) if yaml_match else ""
    body = md[yaml_match.end():] if yaml_match else md

    # Extract abstract from YAML
    abs_match = re.search(r"^abstract:\s*\|\n((?:[ ]{2}.*\n?)+)", yaml, re.MULTILINE)
    if not abs_match:
        raise SystemExit("ERROR: no abstract: | block in YAML")
    abstract = "\n".join(line[2:] for line in abs_match.group(1).split("\n"))

    # Split body by H1
    parts = re.split(r"^(# .+)$", body, flags=re.MULTILINE)
    # parts is [pre, "# 1. ...", body1, "# 2. ...", body2, ...]
    sections: dict[str, str] = {}
    for i in range(1, len(parts), 2):
        header = parts[i]
        content = parts[i + 1] if i + 1 < len(parts) else ""
        sections[header] = content

    return {"abstract": abstract, "sections": sections}


# (last-name -> (year -> bibkey)) mapping for citation substitution.
# Year disambiguates same-author multiple-paper cases (Twinanda 2017 vs 2019,
# Yengera 2018 vs 2019, Loshchilov 2017 vs 2019, Yuan 2024 vs 2025).
CITES = {
    "Twinanda": {"2017": "twinanda2017endonet", "2019": "twinanda2019rsdnet"},
    "Yengera":  {"2018": "yengera2018less", "2019": "yengera2019unsupervised"},
    "Lavanchy": {"2024": "lavanchy2024multibypass"},
    "Loukas":   {"2024": "loukas2024translocal"},
    "Kostopoulos": {"2025": "kostopoulos2025prediction"},
    "Yang":     {"2024": "yang2024surgformer"},
    "Czempiel": {"2020": "czempiel2020tecno"},
    "Liu":      {"2023": "liu2023skit"},
    "Gao":      {"2021": "gao2021transsvnet"},
    "Bose":     {"2025": "bose2025feature"},
    "Kendall":  {"2018": "kendall2018multitask"},
    "Dosovitskiy": {"2021": "dosovitskiy2021vit"},
    "He":       {"2016": "he2016resnet"},
    "Yuan":     {"2024": "yuan2024hecvl", "2025": "yuan2025surgvlp"},
    "Wang":     {"2023": "wang2023endofm"},
    "Schmidgall": {"2024": "schmidgall2024gsvit"},
    "Pedregosa": {"2011": "pedregosa2011sklearn"},
    "Lopez-Paz": {"2016": "lopezpaz2016distillation"},
    "Hoffman":  {"2016": "hoffman2016hallucination"},
    "Radford":  {"2019": "radford2019gpt2"},
    "Ramesh":   {"2021": "ramesh2021mtmstcn"},
}
# two-author and single-author papers (no "et al.")
TWO_AUTHOR_CITES = {
    ("Vapnik", "Vashist", "2009"): "vapnik2009lupi",
    ("Mirza", "Osindero", "2014"): "mirza2014cgan",
    ("Kingma", "Ba", "2015"): "kingma2015adam",
    ("Loshchilov", "Hutter", "2019"): "loshchilov2019adamw",
    ("Loshchilov", "Hutter", "2017"): "loshchilov2017sgdr",
}
SOLO_CITES = {
    ("Wilcoxon", "1945"): "wilcoxon1945ranking",
    ("Wightman", "2019"): "wightman2019timm",
}


def insert_natbib_citations(latex: str) -> str:
    """Convert inline author-year strings to natbib \\citet/\\citep calls.

    Three forms handled:
      1. Narrative:    "Twinanda et al.~(2017)"        -> \\citet
      2. Parenthetical:"(Twinanda et al., 2017)"       -> \\citep
      3. Inline:       "Twinanda et al., 2017"         -> \\citep
         (when not already inside an existing citation context)

    Operates on rendered LaTeX (after pandoc). Conservative: only rewrites
    patterns we have a bibkey for.
    """
    # Form 1: narrative "Author et al.~(YEAR)" -> \citet{key}.
    # \s+ instead of literal " " to span pandoc's line wrapping.
    def _narrative(match):
        last, year = match.group(1), match.group(2)
        key = CITES.get(last, {}).get(year)
        return rf"\citet{{{key}}}" if key else match.group(0)
    latex = re.sub(
        r"\b([A-Z][A-Za-z\-]+)\s+et\s+al\.~?\((\d{4})\)",
        _narrative, latex, flags=re.DOTALL,
    )

    # Form 2: parenthetical "(Author et al., YEAR)" -> \citep{key}
    def _parenth(match):
        last, year = match.group(1), match.group(2)
        key = CITES.get(last, {}).get(year)
        return rf"\citep{{{key}}}" if key else match.group(0)
    latex = re.sub(
        r"\(\s*([A-Z][A-Za-z\-]+)\s+et\s+al\.,\s+(\d{4})\s*\)",
        _parenth, latex, flags=re.DOTALL,
    )

    # Form 3: bare "Author et al., YYYY" (no surrounding parens — appears
    # when refs are chained inside parens, e.g., "(TeCNO, Czempiel et al.,
    # 2020; MTMS-TCN, Ramesh et al., 2021)").
    def _bare(match):
        last, year = match.group(1), match.group(2)
        key = CITES.get(last, {}).get(year)
        return rf"\citealt{{{key}}}" if key else match.group(0)
    latex = re.sub(
        r"\b([A-Z][A-Za-z\-]+)\s+et\s+al\.,\s+(\d{4})\b",
        _bare, latex, flags=re.DOTALL,
    )

    # Two-author papers: "Vapnik & Vashist, 2009" / "Vapnik and Vashist, 2009".
    # Pandoc may render the markdown source's "&" as "\&", and "and" stays as
    # "and"; both forms occur in our manuscript so we accept either.
    for (a1, a2, year), key in TWO_AUTHOR_CITES.items():
        sep = r"(?:\\&|and)"
        # parenthetical form
        latex = re.sub(
            rf"\({a1}\s*{sep}\s*{a2},?\s*{year}\)",
            rf"\\citep{{{key}}}", latex,
        )
        # narrative form
        latex = re.sub(
            rf"{a1}\s*{sep}\s*{a2}\s*\({year}\)",
            rf"\\citet{{{key}}}", latex,
        )
        # bare comma form (e.g., "Vapnik & Vashist, 2009;")
        latex = re.sub(
            rf"{a1}\s*{sep}\s*{a2},?\s*{year}",
            rf"\\citealt{{{key}}}", latex,
        )

    # Solo author: "Wilcoxon, 1945", "Wightman (2019)", ...
    for (author, year), key in SOLO_CITES.items():
        latex = re.sub(
            rf"\({author},?\s*{year}\)",
            rf"\\citep{{{key}}}", latex,
        )
        latex = re.sub(
            rf"\b{author}\s*\({year}(?:--present)?\)",
            rf"\\citet{{{key}}}", latex,
        )
        latex = re.sub(
            rf"\b{author},?\s*{year}",
            rf"\\citealt{{{key}}}", latex,
        )

    return latex


# Unicode → LaTeX substitutions for symbols pandoc doesn't escape under
# pdflatex + [utf8]{inputenc}. Applied to markdown source pre-pandoc so
# the math-mode wrappers survive into the .tex output.
UNICODE_SUB = {
    "≈": r"$\approx$",        # ≈
    "≠": r"$\neq$",           # ≠
    "≤": r"$\leq$",           # ≤
    "≥": r"$\geq$",           # ≥
    "→": r"$\rightarrow$",    # →
    "←": r"$\leftarrow$",     # ←
    "↔": r"$\leftrightarrow$",# ↔
    "↓": r"$\downarrow$",     # ↓
    "↑": r"$\uparrow$",       # ↑
    "×": r"$\times$",         # ×
    "±": r"$\pm$",            # ±
    "−": r"$-$",              # − (minus sign, distinct from hyphen)
    "Δ": r"$\Delta$",         # Δ
    "§": r"\S",               # §
    "✅": r"$\checkmark$",     # ✅ (heavy check)
    "⚠": r"\textbf{!}",       # ⚠ (warning) — fall back to bold !
}


def latex_escape_unicode(text: str) -> str:
    for k, v in UNICODE_SUB.items():
        text = text.replace(k, v)
    return text


def md_to_latex(md_text: str) -> str:
    """Convert markdown to LaTeX via pandoc, then post-process unicode + cites.

    Substitution happens *after* pandoc so we don't have to fight pandoc's
    own dollar-sign math parsing or its escaping of ``$\\pm$``.
    """
    result = subprocess.run(
        ["pandoc", "-f", "markdown", "-t", "latex"],
        input=md_text, capture_output=True, text=True, check=True,
    )
    out = latex_escape_unicode(result.stdout)
    out = insert_natbib_citations(out)
    return out


def main():
    if not SUBMIT_MD.exists():
        sys.exit(f"ERROR: {SUBMIT_MD} not found — run build_short_manuscript.py first")

    parsed = split_md(SUBMIT_MD.read_text())
    sections = parsed["sections"]

    # 1. Abstract — same source for short and long form (single source of truth
    # is the YAML in review_manuscript.md, mirrored into submit_ready.md by
    # build_short_manuscript.py).
    abstract_tex = md_to_latex(parsed["abstract"])
    (LATEX_DIR / "_abstract_short.tex").write_text(abstract_tex)
    (LATEX_DIR / "_abstract.tex").write_text(abstract_tex)

    # 2. Main body: sections 1..9
    main_md_parts = []
    for header, content in sections.items():
        if re.match(r"^# [1-9]\.", header):
            main_md_parts.append(header)
            main_md_parts.append(content.rstrip())
    body_main_tex = md_to_latex("\n".join(main_md_parts))
    (LATEX_DIR / "body_main_short.tex").write_text(body_main_tex)

    # 3. References — natbib + BibTeX. The .bib file is hand-curated at
    # references.bib; this script no longer emits an inline refs_short.tex
    # since main.tex / main_short.tex now use \bibliography{references}.
    # We keep an empty stub for backward compatibility with any external
    # tooling that still expects the file.
    (LATEX_DIR / "refs_short.tex").write_text(
        "% intentionally empty — references are emitted by \\bibliography{references}\n"
    )

    # 4. Appendices (A..F + Z)
    appx_parts = []
    for header, content in sections.items():
        if header.startswith("# Appendix"):
            appx_parts.append(header)
            appx_parts.append(content.rstrip())
    if appx_parts:
        appx_tex = md_to_latex("\n".join(appx_parts))
        (LATEX_DIR / "body_appendix.tex").write_text(appx_tex)

    # Sanity check: count tildes in generated output
    for name in ["_abstract_short.tex", "body_main_short.tex",
                 "refs_short.tex", "body_appendix.tex"]:
        path = LATEX_DIR / name
        if path.exists():
            n = path.read_text().count("~")
            print(f"  {name}: {path.stat().st_size:,} bytes, {n} tildes")


if __name__ == "__main__":
    main()
