"""Build an editable PowerPoint version of fig_project_overall_pipeline.

The original PNG/PDF is generated by build_fig_project_overall_pipeline.py.
This script recreates the same scientific content as native PowerPoint
objects so the diagram can be edited for talks. Real BBP12 frames remain
embedded pictures; boxes, arrows, labels, panels, and annotations are
editable shapes/text.

Output:
    paper/figures/fig_project_overall_pipeline_editable.pptx
"""
from __future__ import annotations

from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile
from xml.sax.saxutils import escape


ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
TEMPLATE = ROOT / "Formatting_Instructions_For_NeurIPS_2026/figures/fig_vit_backbone.pptx"
OUT = ROOT / "figures/fig_project_overall_pipeline_editable.pptx"

LAMBDA_FRAME_DIR = (
    REPO
    / "lambda_mirror/extern/MultiBypass140/datasets/MultiBypass140"
    / "BernBypass70/frames/BBP12"
)
SLIDE_ASSET_DIR = ROOT / "figures_slides/assets"
FRAME_NAMES = [
    "BBP12_00003439.jpg",
    "BBP12_00003444.jpg",
    "BBP12_00003449.jpg",
    "BBP12_00003454.jpg",
    "BBP12_00003459.jpg",
    "BBP12_00003464.jpg",
    "BBP12_00003469.jpg",
    "BBP12_00003474.jpg",
]

EMU_PER_IN = 914_400
SLIDE_W = 13.6
SLIDE_H = 7.0

COLORS = {
    "ink": "111827",
    "muted": "4B5563",
    "edge": "334155",
    "blue": "1D4ED8",
    "blue_light": "EFF6FF",
    "teal": "0F766E",
    "teal_light": "ECFDF5",
    "orange": "D97706",
    "orange_light": "FFF7ED",
    "purple": "7C3AED",
    "purple_light": "F5F3FF",
    "gray": "64748B",
    "gray_light": "F8FAFC",
    "red": "DC2626",
    "red_light": "FEF2F2",
    "green_light": "ECFDF5",
}

shape_id = 1
parts: list[str] = []


def asset_path(name: str) -> Path:
    local = LAMBDA_FRAME_DIR / name
    if local.exists():
        return local
    return SLIDE_ASSET_DIR / name


ASSETS = [asset_path(name) for name in FRAME_NAMES]


def emu(value_in: float) -> str:
    return str(int(round(value_in * EMU_PER_IN)))


def font_size(pt: float) -> str:
    return str(int(round(pt * 100)))


def next_id() -> int:
    global shape_id
    shape_id += 1
    return shape_id


def fill_xml(color: str | None) -> str:
    if color is None:
        return "<a:noFill/>"
    return f'<a:solidFill><a:srgbClr val="{color}"/></a:solidFill>'


def line_xml(
    color: str = COLORS["edge"],
    width_pt: float = 1.0,
    dash: str | None = None,
    no_line: bool = False,
    arrow: bool = False,
) -> str:
    if no_line:
        return "<a:ln><a:noFill/></a:ln>"
    dash_xml = f'<a:prstDash val="{dash}"/>' if dash else ""
    arrow_xml = '<a:tailEnd type="triangle" w="med" h="med"/>' if arrow else ""
    width = int(round(width_pt * 12_700))
    return (
        f'<a:ln w="{width}">'
        f'<a:solidFill><a:srgbClr val="{color}"/></a:solidFill>'
        f"{dash_xml}{arrow_xml}</a:ln>"
    )


def text_body(
    text: str | list[str],
    font_pt: float = 10,
    color: str = COLORS["ink"],
    bold: bool = False,
    align: str = "ctr",
    anchor: str = "ctr",
) -> str:
    lines = text.split("\n") if isinstance(text, str) else text
    bold_flag = "1" if bold else "0"
    paragraphs = []
    for line in lines:
        paragraphs.append(
            f'<a:p><a:pPr algn="{align}"/>'
            f'<a:r><a:rPr sz="{font_size(font_pt)}" b="{bold_flag}">'
            f'<a:solidFill><a:srgbClr val="{color}"/></a:solidFill>'
            f'<a:latin typeface="Arial"/></a:rPr>'
            f"<a:t>{escape(line)}</a:t></a:r></a:p>"
        )
    return (
        f'<p:txBody><a:bodyPr wrap="square" anchor="{anchor}" '
        'lIns="0" rIns="0" tIns="0" bIns="0"><a:spAutoFit/></a:bodyPr>'
        f"<a:lstStyle/>{''.join(paragraphs)}</p:txBody>"
    )


def shape(
    name: str,
    prst: str,
    x: float,
    y: float,
    w: float,
    h: float,
    fill: str | None = None,
    stroke: str = COLORS["edge"],
    stroke_pt: float = 0.9,
    text: str | list[str] | None = None,
    font_pt: float = 10,
    text_color: str = COLORS["ink"],
    bold: bool = False,
    align: str = "ctr",
    anchor: str = "ctr",
    no_line: bool = False,
    dash: str | None = None,
) -> None:
    sid = next_id()
    body = (
        text_body(text, font_pt, text_color, bold, align, anchor)
        if text is not None
        else '<p:txBody><a:bodyPr rtlCol="0" anchor="ctr"/><a:lstStyle/><a:p/></p:txBody>'
    )
    parts.append(
        f'<p:sp><p:nvSpPr><p:cNvPr id="{sid}" name="{escape(name)}"/>'
        f"<p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr>"
        f'<a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/>'
        f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm>'
        f'<a:prstGeom prst="{prst}"><a:avLst/></a:prstGeom>'
        f"{fill_xml(fill)}{line_xml(stroke, stroke_pt, dash=dash, no_line=no_line)}"
        f"</p:spPr>{body}</p:sp>"
    )


def textbox(
    name: str,
    x: float,
    y: float,
    w: float,
    h: float,
    text: str | list[str],
    font_pt: float = 10,
    color: str = COLORS["ink"],
    bold: bool = False,
    align: str = "l",
) -> None:
    sid = next_id()
    parts.append(
        f'<p:sp><p:nvSpPr><p:cNvPr id="{sid}" name="{escape(name)}"/>'
        f'<p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr>'
        f'<a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/>'
        f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm>'
        '<a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr>'
        f"{text_body(text, font_pt, color, bold, align)}</p:sp>"
    )


def line(
    name: str,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    color: str = COLORS["edge"],
    width_pt: float = 1.15,
    arrow: bool = False,
    dash: str | None = None,
) -> None:
    sid = next_id()
    flip_h = x2 < x1
    flip_v = y2 < y1
    x = min(x1, x2)
    y = min(y1, y2)
    w = abs(x2 - x1)
    h = abs(y2 - y1)
    flips = ""
    if flip_h:
        flips += ' flipH="1"'
    if flip_v:
        flips += ' flipV="1"'
    parts.append(
        f'<p:cxnSp><p:nvCxnSpPr><p:cNvPr id="{sid}" name="{escape(name)}"/>'
        f"<p:cNvCxnSpPr/><p:nvPr/></p:nvCxnSpPr><p:spPr>"
        f'<a:xfrm{flips}><a:off x="{emu(x)}" y="{emu(y)}"/>'
        f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm>'
        '<a:prstGeom prst="line"><a:avLst/></a:prstGeom>'
        f"{line_xml(color, width_pt, dash=dash, arrow=arrow)}</p:spPr></p:cxnSp>"
    )


def arrow(x1: float, y1: float, x2: float, y2: float, color: str = COLORS["edge"], dash: bool = False) -> None:
    line("Arrow", x1, y1, x2, y2, color, 1.1, True, "dash" if dash else None)


def picture(name: str, rid: str, x: float, y: float, w: float, h: float, crop_tb: int = 0) -> None:
    sid = next_id()
    crop = f'<a:srcRect t="{crop_tb}" b="{crop_tb}"/>' if crop_tb else ""
    parts.append(
        f'<p:pic><p:nvPicPr><p:cNvPr id="{sid}" name="{escape(name)}"/>'
        '<p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr>'
        f'<p:blipFill><a:blip r:embed="{rid}"/>{crop}'
        '<a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr>'
        f'<a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/>'
        f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm>'
        '<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>'
    )


def block(x: float, y: float, w: float, h: float, text: str, fill: str, stroke: str, font_pt: float = 8.2) -> None:
    shape("Block", "roundRect", x, y, w, h, fill, stroke, 1.0, text, font_pt, COLORS["ink"], True)


def panel_label(x: float, y: float, text: str) -> None:
    textbox("Panel label", x, y, 4.8, 0.22, text, 10.3, COLORS["ink"], True)


def filmstrip(x: float, y: float, w: float, h: float) -> None:
    shape("Filmstrip", "rect", x, y, w, h, "0B0F19", "000000", 0.8)
    for i in range(9):
        yy = y + 0.12 + i * (h - 0.28) / 8
        shape("Film hole left", "rect", x + 0.04, yy, 0.06, 0.05, "FFFFFF", "FFFFFF", 0.1)
        shape("Film hole right", "rect", x + w - 0.10, yy, 0.06, 0.05, "FFFFFF", "FFFFFF", 0.1)
    img_h = 0.19
    for i in range(8):
        yy = y + 0.14 + i * (img_h + 0.045)
        picture(f"Film frame {i + 1}", f"rId{i + 2}", x + 0.15, yy, w - 0.30, img_h, crop_tb=7000)
    textbox("Time label", x + 0.18, y + h + 0.05, w - 0.36, 0.16, "time", 6.8, COLORS["muted"], False, "ctr")
    arrow(x + w / 2, y + h + 0.20, x + w / 2, y + h + 0.48, COLORS["ink"])


def clip_stack(x: float, y: float, w: float, h: float) -> None:
    shape("Clip outline", "roundRect", x, y, w, h, None, COLORS["blue"], 1.0, dash="dash")
    img_h = 0.17
    for i in range(8):
        yy = y + 0.14 + i * (img_h + 0.035)
        picture(f"Clip frame {i + 1}", f"rId{i + 2}", x + 0.12, yy, w - 0.24, img_h, crop_tb=7000)
    textbox("Clip label", x - 0.05, y + h + 0.04, w + 0.10, 0.18, "8-frame clip", 7.8, COLORS["blue"], True, "ctr")


def feature_matrix(x: float, y: float, w: float, h: float) -> None:
    shape("Feature matrix", "rect", x, y, w, h, COLORS["blue_light"], COLORS["blue"], 0.9)
    for i in range(1, 8):
        yy = y + i * h / 8
        line("Matrix row", x, yy, x + w, yy, "BFDBFE", 0.45)
    for r in range(8):
        yy = y + (r + 0.5) * h / 8
        textbox("row label", x - 0.24, yy - 0.05, 0.18, 0.10, f"t_{r + 1}", 5.8, COLORS["ink"], False, "r")
        for c in range(5):
            xx = x + 0.12 + c * (w - 0.24) / 4
            shape("Feature dot", "ellipse", xx - 0.025, yy - 0.025, 0.05, 0.05, COLORS["blue"], COLORS["blue"], 0.1)
    textbox("Tensor label", x - 0.25, y - 0.30, w + 0.50, 0.18, "8 x 768 frame tensor", 7.6, COLORS["blue"], True, "ctr")
    textbox("768 label", x + 0.22, y + h + 0.03, w - 0.44, 0.12, "768", 6.4, COLORS["muted"], False, "ctr")


def phase_sequence(x: float, y: float, w: float, h: float) -> None:
    phases = [("P1", "2563EB"), ("P2", "0F766E"), ("P3", "D97706"), ("P2", "0F766E"), ("P4", "7C3AED"), ("P5", "DB2777")]
    gap = 0.03
    seg_w = (w - gap * (len(phases) - 1)) / len(phases)
    for i, (label, color) in enumerate(phases):
        xx = x + i * (seg_w + gap)
        shape("Phase segment", "rect", xx, y, seg_w, h, color, "FFFFFF", 0.3, label, 5.8, "FFFFFF", True)


def build_slide_xml() -> str:
    shape("Background", "rect", 0, 0, SLIDE_W, SLIDE_H, "FFFFFF", no_line=True)

    textbox("Title", 1.9, 0.10, 9.8, 0.33, "Overall pipeline: workflow-conditioned RSD prediction", 14.2, COLORS["ink"], True, "ctr")
    textbox(
        "Subtitle",
        1.45,
        0.47,
        10.7,
        0.24,
        "Concrete visual example from MultiBypass140 / BBP12; the same model/evaluation protocol is also applied to Cholec80.",
        8.4,
        COLORS["muted"],
        False,
        "ctr",
    )

    panel_label(0.22, 0.96, "1. Video -> clip -> frame tensor")
    textbox("Surgical video", 0.52, 1.27, 1.1, 0.20, "surgical video", 7.8, COLORS["ink"], True, "ctr")
    filmstrip(0.40, 1.55, 1.02, 2.16)
    arrow(1.46, 2.63, 1.82, 2.63, COLORS["blue"])
    clip_stack(1.86, 1.76, 1.06, 1.88)
    arrow(2.96, 2.63, 3.34, 2.63)
    block(3.40, 2.18, 1.10, 0.94, "ViT-B/16\nper-frame\nencoder", COLORS["blue_light"], COLORS["blue"], 7.8)
    arrow(4.55, 2.63, 4.92, 2.63)
    feature_matrix(5.00, 1.96, 1.08, 1.56)

    panel_label(0.22, 4.00, "2. Workflow token: oracle during diagnosis, prefix-derived at inference")
    block(0.40, 4.37, 1.18, 0.57, "full phase\nsequence", COLORS["purple_light"], COLORS["purple"], 7.0)
    phase_sequence(0.53, 5.06, 0.92, 0.18)
    block(1.88, 4.37, 1.10, 0.57, "phase\nbigrams", COLORS["purple_light"], COLORS["purple"], 7.0)
    block(3.40, 4.37, 1.34, 0.57, "TF-IDF\n+ PCA", COLORS["orange_light"], COLORS["orange"], 7.0)
    block(5.16, 4.37, 1.15, 0.57, "k-means\ncentroids", COLORS["orange_light"], COLORS["orange"], 7.0)
    block(6.75, 4.37, 1.25, 0.57, "cluster z\nor posterior q", COLORS["teal_light"], COLORS["teal"], 6.6)
    block(8.48, 4.37, 1.16, 0.57, "workflow\ntoken", COLORS["teal_light"], COLORS["teal"], 7.0)
    textbox("Token formula", 8.30, 5.06, 1.55, 0.18, "E[z,:] or sum_k q_k E[k,:]", 6.7, COLORS["teal"], False, "ctr")
    for x1, x2 in [(1.60, 1.86), (3.00, 3.38), (4.76, 5.14), (6.34, 6.73), (8.02, 8.46)]:
        arrow(x1, 4.66, x2, 4.66, COLORS["gray"])
    textbox("Oracle label", 0.40, 5.57, 1.62, 0.18, "oracle diagnostic path", 6.8, COLORS["purple"], True)
    textbox("Oracle note", 0.40, 5.83, 1.90, 0.18, "uses full-case phase sequence", 6.4, COLORS["muted"])
    block(3.52, 5.55, 1.23, 0.46, "prefix frames", COLORS["blue_light"], COLORS["blue"], 6.6)
    block(5.18, 5.55, 1.28, 0.46, "phase head\npredictions", COLORS["gray_light"], COLORS["gray"], 6.3)
    block(6.88, 5.55, 1.32, 0.46, "same\ncentroid map", COLORS["orange_light"], COLORS["orange"], 6.3)
    textbox(
        "Causal note",
        3.52,
        6.14,
        5.2,
        0.18,
        "causal-at-inference path: no ground-truth phase labels or full-case cluster label",
        6.3,
        COLORS["teal"],
    )
    arrow(4.78, 5.78, 5.16, 5.78, COLORS["teal"])
    arrow(6.48, 5.78, 6.86, 5.78, COLORS["teal"])
    arrow(8.22, 5.78, 8.70, 4.98, COLORS["teal"])

    panel_label(6.55, 0.96, "3. Temporal prediction model")
    block(6.68, 2.26, 1.25, 0.64, "append\nworkflow token", COLORS["teal_light"], COLORS["teal"], 7.0)
    arrow(6.10, 2.63, 6.66, 2.63, COLORS["teal"])
    arrow(9.05, 4.35, 7.32, 2.92, COLORS["teal"])
    block(8.42, 2.05, 1.45, 1.05, "HTA-inspired\n6-block\ntemporal head", COLORS["gray_light"], COLORS["edge"], 7.4)
    arrow(7.96, 2.63, 8.40, 2.63)
    block(10.35, 1.77, 0.95, 0.43, "RSD\nhead", "EEF2FF", COLORS["blue"], 6.8)
    block(10.35, 2.38, 0.95, 0.43, "phase\nhead", "F0FDF4", COLORS["teal"], 6.8)
    block(10.35, 2.99, 0.95, 0.43, "deviation\nhead", COLORS["orange_light"], COLORS["orange"], 6.8)
    arrow(9.90, 2.58, 10.33, 1.98)
    arrow(9.90, 2.58, 10.33, 2.59)
    arrow(9.90, 2.58, 10.33, 3.20)
    block(11.72, 1.99, 1.25, 0.56, "remaining\nsurgery duration", "EEF2FF", COLORS["blue"], 6.8)
    arrow(11.32, 1.98, 11.70, 2.28, COLORS["blue"])

    panel_label(10.02, 4.00, "4. Evaluation question")
    block(10.08, 4.40, 1.12, 0.44, "MB140\nwithin-center", COLORS["green_light"], COLORS["teal"], 6.3)
    block(11.34, 4.40, 1.18, 0.44, "MB140\ncross-center", COLORS["teal_light"], COLORS["teal"], 6.3)
    block(12.68, 4.40, 0.70, 0.44, "Cholec80", COLORS["gray_light"], COLORS["gray"], 6.2)
    block(10.22, 5.24, 1.38, 0.44, "strict prefix-only\nvs centered-window", COLORS["blue_light"], COLORS["blue"], 6.0)
    block(11.84, 5.24, 1.30, 0.44, "shuffled-token\ncontrol", COLORS["purple_light"], COLORS["purple"], 6.0)
    textbox(
        "Main claim",
        10.40,
        6.05,
        2.90,
        0.42,
        "Main claim: workflow conditioning helps when\nworkflow variation exists and the token is meaningful.",
        6.8,
        COLORS["ink"],
        True,
        "ctr",
    )

    line("Footer rule", 0.34, 6.58, 13.25, 6.58, "E5E7EB", 0.7)
    textbox(
        "Footer",
        1.25,
        6.76,
        11.10,
        0.16,
        "Study scope: MultiBypass140 + Cholec80 | conditions: no-token, retrospective oracle, causal-at-inference | metric: validation MAE in minutes",
        6.7,
        COLORS["muted"],
        False,
        "ctr",
    )

    return (
        "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>"
        '<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
        'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        "<p:cSld><p:spTree>"
        '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        "<p:grpSpPr/>"
        f"{''.join(parts)}"
        "</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>"
    )


def build_rels() -> str:
    rels = [
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout7.xml"/>'
    ]
    for idx in range(len(ASSETS)):
        rels.append(
            f'<Relationship Id="rId{idx + 2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/project_pipeline_frame{idx + 1}.jpeg"/>'
        )
    return (
        "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>"
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        f"{''.join(rels)}</Relationships>"
    )


def update_presentation_size(xml: bytes) -> bytes:
    text = xml.decode("utf-8")
    text = text.replace(
        '<p:sldSz cx="12188952" cy="6858000" type="screen4x3"/>',
        f'<p:sldSz cx="{emu(SLIDE_W)}" cy="{emu(SLIDE_H)}" type="custom"/>',
    )
    return text.encode("utf-8")


def main() -> None:
    missing = [str(p) for p in ASSETS if not p.exists()]
    if missing:
        raise FileNotFoundError(f"Missing frame assets: {missing}")

    slide_xml = build_slide_xml().encode("utf-8")
    rels_xml = build_rels().encode("utf-8")
    OUT.parent.mkdir(parents=True, exist_ok=True)

    with ZipFile(TEMPLATE, "r") as zin, ZipFile(OUT, "w", ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            if item.filename in {"ppt/slides/slide1.xml", "ppt/slides/_rels/slide1.xml.rels"}:
                continue
            data = zin.read(item.filename)
            if item.filename == "ppt/presentation.xml":
                data = update_presentation_size(data)
            zout.writestr(item, data)
        zout.writestr("ppt/slides/slide1.xml", slide_xml)
        zout.writestr("ppt/slides/_rels/slide1.xml.rels", rels_xml)
        for idx, asset in enumerate(ASSETS, start=1):
            zout.writestr(f"ppt/media/project_pipeline_frame{idx}.jpeg", asset.read_bytes())

    print(OUT)


if __name__ == "__main__":
    main()
